apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydns
  namespace: default
  labels:
    app: mydns
spec:
  selector:
    matchLabels:
      app: mydns
  replicas: 1
  template:
    metadata:
      labels:
        app: mydns
    spec:
      containers:
        - image: acejilam/landns
          command:
            - "/bin/bash"
            - "-c"
            - "/landns -v -u 114.114.114.114:53 --redis=127.0.0.1:6379 --redis-database=15"
          name: mydns
        - image: redis
          name: redis
---
kind: Service
apiVersion: v1
metadata:
  name: mydns-service
spec:
  type: NodePort
  selector:
    app: mydns
  ports:
    - name: ui
      port: 9353
      targetPort: 9353
      protocol: TCP
      nodePort: 31353
    - name: tcp
      port: 53
      targetPort: 53
      protocol: TCP
      nodePort: 30053
    - name: udp
      port: 53
      targetPort: 53
      protocol: UDP
      nodePort: 30053
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: 30679
#  curl http://192.168.1.100:30053/api/v1 -d 'www.example.com 600 IN A 192.168.1.1'
#  dig www.example.com
