{
 "title": "Landns Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Received Message Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(landns_received_message_count[$__interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Resolve Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (delta(landns_resolve_count[$__interval]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate (In 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (delta(landns_cache_count{cache=\"hit\"}[5m])) / sum by (type) (delta(landns_cache_count[5m]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Resolve Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (source) (delta(landns_resolve_count[$__interval]))",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  {
   "title": "Resolve Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(landns_resolve_duration_seconds_sum[$__interval]) / delta(landns_resolve_duration_seconds_count[$__interval])",
     "legendFormat": "Mean"
    },
    {
     "expr": "landns_resolve_duration_seconds{quantile=\"0.5\"}",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "landns_resolve_duration_seconds{quantile=\"0.9\"}",
     "legendFormat": "90 percentile"
    },
    {
     "expr": "landns_resolve_duration_seconds{quantile=\"0.99\"}",
     "legendFormat": "99 percentile"
    }
   ]
  },
  {
   "title": "Upstream Resolve Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(landns_upstream_resolve_duration_seconds_sum[$__interval]) / delta(landns_upstream_resolve_duration_seconds_count[$__interval])",
     "legendFormat": "Mean"
    },
    {
     "expr": "landns_upstream_resolve_duration_seconds{quantile=\"0.5\"}",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "landns_upstream_resolve_duration_seconds{quantile=\"0.9\"}",
     "legendFormat": "90 percentile"
    },
    {
     "expr": "landns_upstream_resolve_duration_seconds{quantile=\"0.99\"}",
     "legendFormat": "99 percentile"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(landns_resolve_error_count[$__interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (delta(landns_resolve_error_count[$__interval])) / sum by (type) (delta(landns_resolve_count[$__interval]))",
     "legendFormat": "{{ type }}"
    }
   ]
  }
 ]
}